kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: lcrypt-csi-nodeplugin
  namespace: {{ namespace }}
  labels:
    app.kubernetes.io/part-of: lcrypt
    app.kubernetes.io/component: csi-driver
    app.kubernetes.io/name: lcrypt-csi-nodeplugin
spec:
  selector:
    matchLabels:
      app.kubernetes.io/part-of: lcrypt
      app.kubernetes.io/component: csi-driver
      app.kubernetes.io/name: lcrypt-csi-nodeplugin
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: lcrypt
        app.kubernetes.io/component: csi-driver
        app.kubernetes.io/name: lcrypt-csi-nodeplugin
      namespace: {{ namespace }}
    spec:
      # serviceAccountName: lcrypt-csi-nodeplugin
      containers:
        - name: csi-driver-registrar
          image: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v1.3.0
          args:
            - "--csi-address=$(ADDRESS)"
            - "--kubelet-registration-path=$(DRIVER_REG_SOCK_PATH)"
            - "--health-port=9809"
          env:
            - name: ADDRESS
              value: /csi/csi.sock
            - name: DRIVER_REG_SOCK_PATH
              value: {{ kubelet_dir }}/plugins/lcrypt/csi.sock
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: plugin-dir
              mountPath: /csi
            - name: registration-dir
              mountPath: /registration
          ports:
            - containerPort: 9809
              name: healthz
          livenessProbe:
            httpGet:
              path: /healthz
              port: healthz
            initialDelaySeconds: 5
            timeoutSeconds: 5
        - name: lcrypt-nodeplugin
          securityContext:
            privileged: true
            capabilities:
              add: ["SYS_ADMIN"]
            allowPrivilegeEscalation: true
          image: {{ image_name }}
          env:
            - name: NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: CSI_ENDPOINT
              value: unix://plugin/csi.sock
            - name: CSI_ROLE
              value: "nodeplugin"
          volumeMounts:
            - name: plugin-dir
              mountPath: /plugin
            - name: pods-mount-dir
              mountPath: {{ kubelet_dir }}/pods
              mountPropagation: "Bidirectional"
      volumes:
        - name: registration-dir
          hostPath:
            path: {{ kubelet_dir }}/plugins_registry/
            type: Directory
        - name: plugin-dir
          hostPath:
            path: {{ kubelet_dir }}/plugins/lcrypt
            type: DirectoryOrCreate
        - name: pods-mount-dir
          hostPath:
            path: {{ kubelet_dir }}/pods
            type: Directory
