
kind: Deployment
apiVersion: apps/v1
metadata:
  name: csi-crypt-provisioner
  labels:
    app.kubernetes.io/part-of: csi-crypt
    app.kubernetes.io/component: csi-driver
    app.kubernetes.io/name: csi-crypt-provisioner
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/part-of: csi-crypt
      app.kubernetes.io/component: csi-driver
      app.kubernetes.io/name: csi-crypt-provisioner
  template:
    metadata:
      name: csi-provisioner
      labels:
        app.kubernetes.io/part-of: csi-crypt
        app.kubernetes.io/component: csi-driver
        app.kubernetes.io/name: csi-crypt-provisioner
    spec:
      serviceAccountName: csi-crypt-provisioner
      containers:
        - name: csi-provisioner
          image: k8s.gcr.io/sig-storage/csi-provisioner:v2.1.0
          args:
            - "--csi-address=$(ADDRESS)"
            - "--timeout=3m"
            - "--leader-election"
            - "--http-endpoint=:8080"
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
          ports:
            - containerPort: 8080
              name: http-endpoint
              protocol: TCP
          livenessProbe:
            failureThreshold: 1
            httpGet:
              path: /healthz/leader-election
              port: http-endpoint
            initialDelaySeconds: 10
            timeoutSeconds: 10
            periodSeconds: 20
          resources: {}
        - name: csi-attacher
          image: k8s.gcr.io/sig-storage/csi-attacher:v3.0.0
          args:
            - "--v=5"
            - "--csi-address=$(ADDRESS)"
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
          resources: {}
        - name: csi-crypt-provisioner
          securityContext:
            privileged: true
            capabilities:
              add: ["CAP_SYS_ADMIN", "SYS_ADMIN"]
            allowPrivilegeEscalation: true
          image: ghcr.io/lykos153/csi-crypt:main
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: CSI_ENDPOINT
              value: unix://plugin/csi.sock
            - name: CSI_ROLE
              value: "provisioner"
          volumeMounts:
            - name: socket-dir
              mountPath: /plugin
          resources: {}
      volumes:
        - name: socket-dir
          emptyDir: {}
