apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-crypt
provisioner: de.silvio-ankermann.csi-crypt
# parameters:
#   type: gp2
reclaimPolicy: Retain
allowVolumeExpansion: false
# mountOptions:
#   - debug
volumeBindingMode: WaitForFirstConsumer
parameters:
  csi.storage.k8s.io/node-publish-secret-name: ${pvc.annotations['de.silvio-ankermann.csi-crypt/key']}
  csi.storage.k8s.io/node-publish-secret-namespace: ${pvc.namespace}
