apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ encrypterName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/part-of: lcrypt
      app.kubernetes.io/component: csi-driver
      app.kubernetes.io/name: encrypter
      app.kubernetes.io/image: {{ imageName }}
      app.kubernetes.io/volume-id: {{ volumeId }}
  template:
    metadata:
      name: encrypter-{{ volumeId }}
      labels:
        app.kubernetes.io/part-of: lcrypt
        app.kubernetes.io/component: csi-driver
        app.kubernetes.io/name: encrypter
        app.kubernetes.io/image: {{ imageName }}
        app.kubernetes.io/volume-id: {{ volumeId }}
    spec:
      nodeName: {{ nodeName }}
      containers:
        - name: encrypter
          image: {{ imageName }}
          stdin: true #debugging
          tty: true #debugging
          securityContext:
            privileged: true
          volumeMounts:
            - name: pods-mount-dir
              mountPath: {{ kubeletDir }}/pods
              mountPropagation: "Bidirectional"
            - name: storage-backend
              mountPath: /storage
      volumes:
        - name: pods-mount-dir
          hostPath:
            path: {{ kubeletDir }}/pods
            type: Directory
        - name: storage-backend
          persistentVolumeClaim:
            claimName: {{ backendClaimName }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ backendClaimName }}
spec:
  storageClassName: {{ backendStorageClass }}
  resources:
    requests:
      storage: {{ backendCapacity }}
  accessModes:
    - ReadWriteOnce
