kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: lcrypt-csi-nodeplugin
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/part-of: lcrypt
    app.kubernetes.io/component: csi-driver
    app.kubernetes.io/name: lcrypt-csi-nodeplugin
spec:
  selector:
    matchLabels:
      app.kubernetes.io/part-of: lcrypt
      app.kubernetes.io/component: csi-driver
      app.kubernetes.io/name: lcrypt-csi-nodeplugin
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: lcrypt
        app.kubernetes.io/component: csi-driver
        app.kubernetes.io/name: lcrypt-csi-nodeplugin
      namespace: {{ .Values.namespace }}
    spec:
      serviceAccountName: lcrypt-csi-nodeplugin
      imagePullSecrets:
        - name: {{ .Values.pullSecret }}
      containers:
        - name: csi-driver-registrar
          image: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v1.3.0
          args:
            - "--csi-address=$(ADDRESS)"
            - "--kubelet-registration-path=$(DRIVER_REG_SOCK_PATH)"
          env:
            - name: ADDRESS
              value: /csi/csi.sock
            - name: DRIVER_REG_SOCK_PATH
              value: {{ .Values.kubeletDir }}/plugins/lcrypt/csi.sock
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: plugin-dir
              mountPath: /csi
            - name: registration-dir
              mountPath: /registration
        - name: lcrypt-nodeplugin
          securityContext:
            privileged: true
            capabilities:
              add: ["SYS_ADMIN"]
            allowPrivilegeEscalation: true
          image: {{ .Values.imageName }}
          {{- if .Values.nodeplugin.debug }}
          stdin: true
          tty: true
          {{- end }}
          env:
            - name: NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: CSI_ENDPOINT
              value: unix://plugin/csi.sock
            - name: CSI_ROLE
              value: "nodeplugin"
            {{- if .Values.nodeplugin.debug }}
            - name: DEBUG
              value: "true"
            {{- end }}
          volumeMounts:
            - name: plugin-dir
              mountPath: /plugin
            - name: pods-mount-dir
              mountPath: {{ .Values.kubeletDir }}/pods
              mountPropagation: "Bidirectional"
      volumes:
        - name: registration-dir
          hostPath:
            path: {{ .Values.kubeletDir }}/plugins_registry/
            type: Directory
        - name: plugin-dir
          hostPath:
            path: {{ .Values.kubeletDir }}/plugins/lcrypt
            type: DirectoryOrCreate
        - name: pods-mount-dir
          hostPath:
            path: {{ .Values.kubeletDir }}/pods
            type: Directory
