
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: lcrypt-csi-provisioner
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/part-of: lcrypt
    app.kubernetes.io/component: csi-driver
    app.kubernetes.io/name: lcrypt-csi-provisioner
spec:
  serviceName: lcrypt-csi-provisioner
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/part-of: lcrypt
      app.kubernetes.io/component: csi-driver
      app.kubernetes.io/name: lcrypt-csi-provisioner
  template:
    metadata:
      name: csi-provisioner
      namespace: {{ .Values.namespace }}
      labels:
        app.kubernetes.io/part-of: lcrypt
        app.kubernetes.io/component: csi-driver
        app.kubernetes.io/name: lcrypt-csi-provisioner
    spec:
      serviceAccountName: lcrypt-csi-provisioner
      imagePullSecrets:
        - name: {{ .Values.pullSecret }}
      containers:
        - name: csi-provisioner
          image: k8s.gcr.io/sig-storage/csi-provisioner:v2.1.0
          args:
            - "--csi-address=$(ADDRESS)"
            - "--timeout=3m"
            - "--leader-election"
            - "--http-endpoint=:8080"
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
          ports:
            - containerPort: 8080
              name: http-endpoint
              protocol: TCP
          livenessProbe:
            failureThreshold: 1
            httpGet:
              path: /healthz/leader-election
              port: http-endpoint
            initialDelaySeconds: 10
            timeoutSeconds: 10
            periodSeconds: 20
        - name: csi-attacher
          image: k8s.gcr.io/sig-storage/csi-attacher:v3.0.0
          args:
            - "--v=5"
            - "--csi-address=$(ADDRESS)"
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
        - name: lcrypt-provisioner
          securityContext:
            privileged: true
            capabilities:
              add: ["CAP_SYS_ADMIN", "SYS_ADMIN"]
            allowPrivilegeEscalation: true
          image: {{ .Values.imageName }}
          {{- if .Values.provisioner.debug }}
          stdin: true
          tty: true
          {{- end }}
          env:
            - name: NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: CSI_ENDPOINT
              value: unix://plugin/csi.sock
            - name: CSI_ROLE
              value: "provisioner"
            {{- if .Values.provisioner.debug }}
            - name: DEBUG
              value: "true"
            {{- end }}
          volumeMounts:
            - name: socket-dir
              mountPath: /plugin
      volumes:
        - name: socket-dir
          emptyDir:
