apiVersion: v1
kind: ServiceAccount
metadata:
  name: lcrypt-csi-nodeplugin
  namespace: {{ .Values.namespace }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: {{ .Values.namespace }}
  name: lcrypt-csi-nodeplugin-backend-creation
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "watch", "list", "delete", "update", "create"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch", "list", "delete", "update", "create"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["watch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: lcrypt-csi-nodeplugin
  namespace: {{ .Values.namespace }}
subjects:
  - kind: ServiceAccount
    name: lcrypt-csi-nodeplugin
    namespace: {{ .Values.namespace }}
roleRef:
  kind: Role
  name: lcrypt-csi-nodeplugin-backend-creation
  apiGroup: rbac.authorization.k8s.io

# The following role is necessary to get the current nodes labels by name
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: lcrypt-csi-nodeplugin-list-nodes
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["list"]
---
  kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: lcrypt-csi-nodeplugin
subjects:
  - kind: ServiceAccount
    name: lcrypt-csi-nodeplugin
    namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: lcrypt-csi-nodeplugin-list-nodes
  apiGroup: rbac.authorization.k8s.io
