apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: lcrypt
provisioner: lcrypt
# parameters:
#   type: gp2
reclaimPolicy: Retain
allowVolumeExpansion: false
# mountOptions:
#   - debug
volumeBindingMode: WaitForFirstConsumer
